spring:
  application:
    name: Enjoying

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/enjoying
    username: postgres
    password: mirlan001m.

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


server:
  error:
    include-stacktrace: always


app:
  jwt:
    secret: Employees